// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Change } from './change';


export class ChangeRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChangeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChangeRequest(bb:flatbuffers.ByteBuffer, obj?:ChangeRequest):ChangeRequest {
  return (obj || new ChangeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChangeRequest(bb:flatbuffers.ByteBuffer, obj?:ChangeRequest):ChangeRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChangeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

documentId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

changes(index: number, obj?:Change):Change|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Change()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

changesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startChangeRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDocumentId(builder:flatbuffers.Builder, documentId:number) {
  builder.addFieldInt32(0, documentId, 0);
}

static addChanges(builder:flatbuffers.Builder, changesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, changesOffset, 0);
}

static createChangesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChangesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endChangeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChangeRequest(builder:flatbuffers.Builder, documentId:number, changesOffset:flatbuffers.Offset):flatbuffers.Offset {
  ChangeRequest.startChangeRequest(builder);
  ChangeRequest.addDocumentId(builder, documentId);
  ChangeRequest.addChanges(builder, changesOffset);
  return ChangeRequest.endChangeRequest(builder);
}
}
