// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ChangeResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChangeResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChangeResponse(bb:flatbuffers.ByteBuffer, obj?:ChangeResponse):ChangeResponse {
  return (obj || new ChangeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChangeResponse(bb:flatbuffers.ByteBuffer, obj?:ChangeResponse):ChangeResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChangeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startChangeResponse(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endChangeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChangeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  ChangeResponse.startChangeResponse(builder);
  return ChangeResponse.endChangeResponse(builder);
}
}
