// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetRequest(bb:flatbuffers.ByteBuffer, obj?:GetRequest):GetRequest {
  return (obj || new GetRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetRequest(bb:flatbuffers.ByteBuffer, obj?:GetRequest):GetRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

documentId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDocumentId(builder:flatbuffers.Builder, documentId:number) {
  builder.addFieldInt32(0, documentId, 0);
}

static endGetRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetRequest(builder:flatbuffers.Builder, documentId:number):flatbuffers.Offset {
  GetRequest.startGetRequest(builder);
  GetRequest.addDocumentId(builder, documentId);
  return GetRequest.endGetRequest(builder);
}
}
