// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Request, unionToRequest, unionListToRequest } from './request';


export class RequestHolder {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RequestHolder {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRequestHolder(bb:flatbuffers.ByteBuffer, obj?:RequestHolder):RequestHolder {
  return (obj || new RequestHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRequestHolder(bb:flatbuffers.ByteBuffer, obj?:RequestHolder):RequestHolder {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RequestHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestType():Request {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Request.NONE;
}

request<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startRequestHolder(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRequestType(builder:flatbuffers.Builder, requestType:Request) {
  builder.addFieldInt8(0, requestType, Request.NONE);
}

static addRequest(builder:flatbuffers.Builder, requestOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, requestOffset, 0);
}

static endRequestHolder(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRequestHolder(builder:flatbuffers.Builder, requestType:Request, requestOffset:flatbuffers.Offset):flatbuffers.Offset {
  RequestHolder.startRequestHolder(builder);
  RequestHolder.addRequestType(builder, requestType);
  RequestHolder.addRequest(builder, requestOffset);
  return RequestHolder.endRequestHolder(builder);
}
}
