// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ChangeRequest } from './change-request';
import { GetRequest } from './get-request';


export enum Request {
  NONE = 0,
  GetRequest = 1,
  ChangeRequest = 2
}

export function unionToRequest(
  type: Request,
  accessor: (obj:ChangeRequest|GetRequest) => ChangeRequest|GetRequest|null
): ChangeRequest|GetRequest|null {
  switch(Request[type]) {
    case 'NONE': return null; 
    case 'GetRequest': return accessor(new GetRequest())! as GetRequest;
    case 'ChangeRequest': return accessor(new ChangeRequest())! as ChangeRequest;
    default: return null;
  }
}

export function unionListToRequest(
  type: Request, 
  accessor: (index: number, obj:ChangeRequest|GetRequest) => ChangeRequest|GetRequest|null, 
  index: number
): ChangeRequest|GetRequest|null {
  switch(Request[type]) {
    case 'NONE': return null; 
    case 'GetRequest': return accessor(index, new GetRequest())! as GetRequest;
    case 'ChangeRequest': return accessor(index, new ChangeRequest())! as ChangeRequest;
    default: return null;
  }
}
