// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ChangeResponse } from './change-response';
import { DocumentElement } from './document-element';


export enum Response {
  NONE = 0,
  ChangeResponse = 1,
  DocumentElement = 2
}

export function unionToResponse(
  type: Response,
  accessor: (obj:ChangeResponse|DocumentElement) => ChangeResponse|DocumentElement|null
): ChangeResponse|DocumentElement|null {
  switch(Response[type]) {
    case 'NONE': return null; 
    case 'ChangeResponse': return accessor(new ChangeResponse())! as ChangeResponse;
    case 'DocumentElement': return accessor(new DocumentElement())! as DocumentElement;
    default: return null;
  }
}

export function unionListToResponse(
  type: Response, 
  accessor: (index: number, obj:ChangeResponse|DocumentElement) => ChangeResponse|DocumentElement|null, 
  index: number
): ChangeResponse|DocumentElement|null {
  switch(Response[type]) {
    case 'NONE': return null; 
    case 'ChangeResponse': return accessor(index, new ChangeResponse())! as ChangeResponse;
    case 'DocumentElement': return accessor(index, new DocumentElement())! as DocumentElement;
    default: return null;
  }
}
